- hosts: local
  user: cloud
  sudo: yes

  tasks:
    - name: apt cache is up-to-date
      apt:
        update_cache=yes
        cache_valid_time=1

    - name: system is up-to-date
      apt:
        upgrade=full

    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - apache2
        - php5
        - libapache2-mod-php5

    - name: apache running
      service:
        name=apache2
        state=running
        enabled=yes

    - name: move default apache site
      shell: mv /var/www/html /var/www/default

    - name: deploy
      git:
        repo=https://github.com/aurelienmaury/cw-bundle-lamp.git
        dest=/var/www/html
